sudo: required

language: go

go:
- 1.9.3

services:
- docker

env:
  global:
  - secure: badEBMt9w8c3mFpZ16aD1CvNEL3QGYPzxqX/kqJfhUXQmf4jo6vgtMVdM14+ddl7g6SS8gKzpqWazkskEC+toUCobQNSf5MRqALeTs2S5CBBZt1slLj8iZOWLe4LT109RRMEOsUFgIU9Ub8Cnky/0HbPVid8Mbyeu5LAAAjIE3YGozEh8URGDYjCGcRRqmM8N0F4BLWgZkN0/muLZ2QJ6SoSJ4Qvj18k351e5xOR100N+hiWLaIZ04hXl+joR94MyjGShf943x+ltU6gWB0GuVBZfLAbzcXwm0q70x99Xqhbl6kh+xnuPtodf0y+96JYaJE58BVfuqNa4kWPSD7l/JvOuMjyduLLu4qcFUov9U5msLFtEflqxXB5vvPVwfS1RCL5D9jOT9M3AxAig7VjH6HWWv3rzq7ieDbNo+SlmCEjYr4PS2xl0sPHbTGu1udgub5MwSJG0CvKVofIkzuZqdhiJI8SN/v/qUIMePvrL9HpCK9qgPJv5W2Zgff4IlRENRuctELb9n+PUQwgFtxVT6vTPpgBJSPOSVWdzkQ9t1V57z4f1+dZUtoeBEWXlMO9T3PAg2HADJzk4CXw2TrlwleD94v5BJHSbaGqneq3k40+7H+pmCVqlVE6ujP1P8YsbVUHzmdqZ2vxzG+jylFfdaZrQs4/Oa+K56idjgwIL7E=
  - secure: VDK/bm1XPVvX/sd45a0+BuWGr+Hp0XZ/rwF1uUy4yPJcyVRRcCTeqkdTyqjy4eZR5QMNGjQHzCHf4dlLHddOYKNMB2uCkqXMKSRl6rvg3r4K/enmy7kXuy+B5/YMvaoZ/ob4y6yoUACpBsUGvsscQdiZYr8SEcfb5swfPZoew9dGckQ6cHpaVkJDo4JRXvTuSYsmNC8cI6hNpO7fbxFBT2bPSMDPBFbn1vnG+yojfoCMbcOi0UbswSMvt/gf33cZTUStNdvD2HlhfZlNmfyCBD/HZ4ABBQGE3jj1+eLKcKrNyswJqTlHfhC5CLWetScE8esO2UPtu4X86ioZLsiKsE5hpB6VuNmtA35Tzrqrqgd5026I3gzURjG9Qtr1FJ/ewje937Dpubv67LAvQ/bBsXdAfwudB+uqpKqY/1Di0hGxu16SvBhEK6YP7GGqHGQ9owjl5chPfhASUhChtm1crochXFjheH04fKcWhCGmkn3yn+sXe2fSGJdAJ/Jr1Uj4VXl/wneWPUsGopWelu95+oPoybRXKkuzkPJex7Yckv5hE7ERXoZW70ziobU2M18jwstCY4yG9M+aAnQlHDOQaI9lEeMwVtJP5vXWdPZ6emn38IIoeVyU7Zd0BNUs0rAvN+WmNalqIFU8WPKrB+QLWN28/NmI1wi306V25LTyJIw=

install:
- make install_ci
- make install

script:
- make test
- make lint

after_success:
- if [ "$TRAVIS_BRANCH" != "master" ]; then SKIP_DOCKER=true; fi
- test $SKIP_DOCKER || docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" quay.io
- test $SKIP_DOCKER || docker build -t quay.io/frankgreco/tester -t quay.io/frankgreco/tester:${TRAVIS_COMMIT} .
- test $SKIP_DOCKER || docker push quay.io/frankgreco/tester:${TRAVIS_COMMIT}
- test $SKIP_DOCKER || docker push quay.io/frankgreco/tester